# subset algo


In [18]:
import numpy as np
def subset(elements: list, weight: int):
    def rec(i: int, w: int):
        if i == -1:
            if w == -1:
                return 0
            else:
                return -float('inf')
            
        el = elements[i]

        if OPT[i, w] == 0:
            OPT[i, w] = max(rec(i-1, w), el + rec(i-1, w-el))

        return OPT[i, w]

    length = len(elements)
    OPT = np.zeros((length, weight))
    val = rec(length-1, weight-1)
    print(OPT)
    return val


elements = [1, 2, 4]
weight = 8

subset(elements, weight)

[[  0. -inf   0. -inf   0. -inf   0. -inf]
 [  0.   0.   0. -inf   0.   0.   0. -inf]
 [  0.   0.   0.   0.   0.   0.   0. -inf]]


-inf

In [25]:
import numpy as np
def subset(elements: list, weight: int):
    
    elements = [0] + elements
    length = len(elements)
    OPT = np.zeros((length, weight+1))

    for i in range(length):
        el = elements[i]
        for j in range(weight+1):
            if i == 0 or j == 0:
                OPT[i, j] = 0
            elif el <= j:
                OPT[i, j] = max(OPT[i-1, j], el + OPT[i-1, j-el])
            else:
                OPT[i, j] = OPT[i-1, j]

    print(OPT)
    return OPT[length-1, weight]

elements = [1, 2, 4, 1, 5]
weight = 9

subset(elements, weight)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 3. 3. 3. 3. 3. 3. 3.]
 [0. 1. 2. 3. 4. 5. 6. 7. 7. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 8.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


9.0

In [32]:
queue = [-float('inf')] *2

elements = [1, 2, 4, 1, 5]

for i in elements:
    print(i)
    if i > queue[0]:
        queue.append(i)
        queue.pop(0)
print(queue)

    

1
2
4
1
5
[4, 5]
