In [3]:
import numpy as np
a = [1,2,3,4,5,5,100]
np.bincount(a)

array([0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [4]:
def class_prop(y):
    count = np.bincount(y)
    count = count[count > 0]  # Exclude zero counts
    proposition = count / y.size
    return proposition

def class_prop2(y):
    _, count = np.unique(y, return_counts=True)
    print(count)
    proposition = count / y.size
    return proposition

y = np.array([-1,-1,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8])

propositions = class_prop(y)
print(np.log2(propositions.size))
np.sum(propositions)
print(propositions)

- np.sum(propositions* np.log2(propositions))

ValueError: 'list' argument must have no negative elements

In [4]:
a = np.array([1, 2, 3, 4, 5, 2])
# returns a boolean mask of values lower than 3
new_array = a <= 3
for i in new_array:
    print(new_array)

[ True  True  True False False  True]
[ True  True  True False False  True]
[ True  True  True False False  True]
[ True  True  True False False  True]
[ True  True  True False False  True]
[ True  True  True False False  True]


In [5]:

array = np.array([-1, -1, 1, 2, 3, 4, 5, 2])
count = np.bincount(array)
print(np.argmax(count))



ValueError: 'list' argument must have no negative elements

In [12]:
import numpy as np
array = np.array([-1, -1, 1, 2, 3, 4, 5, 2])
mask = np.array([True, True, False, False, False, False, False, False])
array[~mask]

array([1, 2, 3, 4, 5, 2])

In [8]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [1]:
import numpy as np

features = np.array([[1, 2], 
                     [4, 5]
                     [1, 2]])


features.shape

(2, 3)

In [8]:
import numpy as np
w = np.array([1,1,0,1,0])
my = 0.01
nabla = np.array([3.4, 1.7, 1.7, 5.1, -0.2])
w2 = w - my * nabla

def foreward(x, w):
    z = (x[0]*w[0]) + (x[1]*w[1]) + w[2]
    g = max(0, z)
    y = (g*w[3]) + w[4]
    return y

cost = ((foreward([2,1], w2)-1.3)**2 + (foreward([-3,2], w2)-1.9)**2)/2

print(cost)

2.855647324401999


In [1]:
9990 - 49

9941

In [ ]:
from sklearn import metrics

# 9990 working 10 not working
a = 9990*[1] + 10*[0]

# first guess is guesses all workiing
b = 10000*[1]

# seccond guess is 49 false pos and 9 false neg
c = 49 * [0] + 9941 * [1] + 9 * [0] + 1 * [1]

#weighted f1 score
f1 = metrics.f1_score(a, b, average='weighted')
print(f1)

f1 = metrics.f1_score(a, c, average='weighted')
print(f1)

# precision
precision = metrics.precision_score(a, b, average='binary')
print(precision)

precision = metrics.precision_score(a, c, average='weighted')
print(precision)


# balanced accuracy
balanced_accuracy = metrics.balanced_accuracy_score(a, b)
print(balanced_accuracy)

balanced_accuracy = metrics.balanced_accuracy_score(a, c)
print(balanced_accuracy)    

metrics.accuracy_score(a, b)    

0.9985002501250625
0.9967586854127564
0.999
0.9990546896135516
0.5
0.9475475475475476


In [30]:
from decimal import Decimal, getcontext

# Set the precision high enough to avoid floating-point errors
getcontext().prec = 10

old_b = Decimal('0.8')
old_w = Decimal('1.2')
lambda_ = Decimal('0.05')
def f(x): return Decimal('1.2') * Decimal(x) + Decimal('0.8')

def b(x,y) -> float: return -4 * (Decimal(y) - f(x))**3

def w(x,y) -> float: return -4 * x * (Decimal(y) - f(x))**3


n_b = old_b - lambda_ *  ( b(2,3) + b(3,4) )
n_w = old_w - lambda_ *  ( w(2,3) + w(3,4) )
print(n_b)
print(n_w)

print (b(2,3) + b(3,4))
print (w(2,3) + w(3,4))


0.78560
1.15840
0.288
0.832
